### ISSUE TITLE
Establish a budget

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#3] opened 2015-10-25 17:36 UTC
Get a definitive budget from Brian

**Comment by joshuarichard** [comment] 2015-10-25 17:46
Emailed him a week ago and he's since gotten back to me on this. He needs to fill out some forms on his end but we should be on to one soon for github private and 6 round trip tickets to guatemala.

**Comment by joshuarichard** [comment] 2015-10-27 21:49
We spoke with Brian over skype and he confirmed for us that AMG can pay for private github accounts. He's also looking into getting us a travel budget, but this requires more time.

**Comment by joshuarichard** [comment] 2015-10-27 22:41
Closing this because Brian's working on it and the rest is out of our control. There is no "set" budget, just make a list of things you need as you go and send Brian the receipt

**Closed as completed by joshuarichard** 2015-10-27 22:41 UTC
